
version: '3.0'

services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./php_code:/var/www/html/
  db:
    image: mariadb:10.8.2-rc-focal
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    links:
      - db
    ports:
      - "8080:80"
