version: "3"

services:

  nginx: # web server (reverse proxy) and load balancer for frontend and backend
      image: nginx:1.19.10-alpine
      container_name: nginx
      restart: always
      ports:
        - "8080:8080"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - frontend
        - backend
        - vscodeweb

  frontend: # frontend angular
    container_name: frontend_angular
    build: ./frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"

  backend: # backend python fastapi
    container_name: backend_fastapi
    build: ./backend
    restart: always
    links:
      - database
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: user
      DB_NAME: database
    volumes:
      - ./backend/src:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8080 --root-path='/api' --reload" #DEBUG: sh -c "python3 main.py"

  database: # database mariadb (mysql based)
    container_name: database_mariadb
    image: mariadb:11.1.2-jammy
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: database
    volumes:
      - ./database/persistence:/var/lib/mysql

  adminer: # database management integrated in web browser
    container_name: admin_database_panel
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - "8081:8080"
    links:
      - database

  vscode: # vscode server
    container_name: vscode
    build: ./vscode
    restart: always